export const AIRCRAFT_TYPES = {
  cessna_172: {
    name: 'Cessna 172',
    mass: 1100,
    maxThrust: 16000,
    wingArea: 16,
    pitchRate: 1.8,
    rollRate: 2.8,
    yawRate: 0.8,
    stallAoa: 30 * (Math.PI / 180),
    takeoffSpeed: 55,
    scale: 0.8,
    type: 'prop',
    // Visual config
    fuselageLength: 8,
    fuselageRadius: 0.7,
    wingSpan: 11,
    wingSweep: 0,
    tailHeight: 2.5,
    engineCount: 1,
    color: 0xeeeeee,
    accentColor: 0x1144aa,
    cockpitY: 0.18,
    cockpitZ: -2.55,
    fuelCapacity: 212,
    fuelBurnRate: 40,
    spoolRate: 50,
    idleN1: 22,
    engineStartTime: 3,
    glassPanel: false,
    audioType: 'piston',
    hasAfterburner: false,
  },
  boeing_737: {
    name: 'Boeing 737',
    mass: 35000,
    maxThrust: 260000,
    wingArea: 125,
    pitchRate: 0.8,
    rollRate: 1.4,
    yawRate: 0.4,
    stallAoa: 28 * (Math.PI / 180),
    takeoffSpeed: 80,
    scale: 2.5,
    type: 'jet',
    fuselageLength: 14,
    fuselageRadius: 1.2,
    wingSpan: 14,
    wingSweep: 0.4,
    tailHeight: 3.8,
    engineCount: 2,
    color: 0xf0f0f0,
    accentColor: 0x0055aa,
    cockpitY: 0.58,
    cockpitZ: -5.15,
    fuelCapacity: 26000,
    fuelBurnRate: 2800,
    spoolRate: 20,
    idleN1: 25,
    engineStartTime: 5,
    glassPanel: true,
    audioType: 'jet',
    hasAfterburner: false,
  },
  f16: {
    name: 'F-16 Falcon',
    mass: 8500,
    maxThrust: 180000,
    wingArea: 28,
    pitchRate: 3.5,
    rollRate: 6.0,
    yawRate: 1.8,
    stallAoa: 45 * (Math.PI / 180),
    takeoffSpeed: 70,
    scale: 1.2,
    type: 'fighter',
    fuselageLength: 10,
    fuselageRadius: 0.6,
    wingSpan: 10,
    wingSweep: 0.7,
    tailHeight: 3.0,
    engineCount: 1,
    color: 0x888888,
    accentColor: 0x556655,
    cockpitY: 0.38,
    cockpitZ: -2.72,
    fuelCapacity: 3200,
    fuelBurnRate: 4500,
    spoolRate: 25,
    idleN1: 28,
    engineStartTime: 4,
    glassPanel: false,
    audioType: 'jet',
    hasAfterburner: true,
  },
  airbus_a320: {
    name: 'Airbus A340',
    mass: 65000,
    maxThrust: 500000,
    wingArea: 362,
    pitchRate: 0.6,
    rollRate: 1.0,
    yawRate: 0.3,
    stallAoa: 26 * (Math.PI / 180),
    takeoffSpeed: 80,
    scale: 3.2,
    type: 'jet',
    fuselageLength: 18,
    fuselageRadius: 1.4,
    wingSpan: 18,
    wingSweep: 0.45,
    tailHeight: 4.5,
    engineCount: 4,
    color: 0xffffff,
    accentColor: 0x003366,
    cockpitY: 0.68,
    cockpitZ: -6.65,
    fuelCapacity: 24000,
    fuelBurnRate: 2600,
    spoolRate: 20,
    idleN1: 25,
    engineStartTime: 6,
    glassPanel: true,
    audioType: 'jet',
    hasAfterburner: false,
  },
  extra_300: {
    name: 'Extra 300 (Aerobatic)',
    mass: 680,
    maxThrust: 12000,    // high T/W for vertical climbs and sustained inverted flight
    wingArea: 10.5,
    pitchRate: 5.5,
    rollRate: 7.0,       // snap rolls
    yawRate: 3.0,
    stallAoa: 0.52,      // ~30 degrees — symmetric airfoil, very hard to stall
    takeoffSpeed: 28,
    scale: 0.7,
    type: 'prop',
    isSeaplane: false,
    fuselageLength: 6.5,
    fuselageRadius: 0.55,
    wingSpan: 8.0,
    wingSweep: 0,
    tailHeight: 2.0,
    engineCount: 1,
    color: 0xffffff,
    accentColor: 0xdd2222,
    cockpitY: 1.2,
    cockpitZ: 1.5,
    fuelCapacity: 120,
    fuelBurnRate: 50,
    spoolRate: 50,
    idleN1: 22,
    engineStartTime: 2,
    glassPanel: false,
    audioType: 'piston',
    hasAfterburner: false,
  },
  dhc2_beaver: {
    name: 'DHC-2 Beaver (Seaplane)',
    mass: 2300,
    maxThrust: 22000,
    wingArea: 23,
    pitchRate: 1.5,
    rollRate: 2.2,
    yawRate: 0.7,
    stallAoa: 28 * (Math.PI / 180),
    takeoffSpeed: 50,
    scale: 0.9,
    type: 'prop',
    isSeaplane: true,
    // Visual config
    fuselageLength: 9,
    fuselageRadius: 0.75,
    wingSpan: 14,
    wingSweep: 0,
    tailHeight: 2.8,
    engineCount: 1,
    color: 0xeeeeee,
    accentColor: 0xcc3333,
    cockpitY: 0.2,
    cockpitZ: -2.75,
    fuelCapacity: 340,
    fuelBurnRate: 70,
    spoolRate: 50,
    idleN1: 22,
    engineStartTime: 3,
    glassPanel: false,
    audioType: 'piston',
    hasAfterburner: false,
  },
};

export function getAircraftType(name) {
  return AIRCRAFT_TYPES[name] || AIRCRAFT_TYPES.cessna_172;
}

export function getAircraftList() {
  return Object.entries(AIRCRAFT_TYPES).map(([key, val]) => ({
    key,
    name: val.name,
    type: val.type,
  }));
}
